cmake_minimum_required(VERSION 3.20)
project(CryptoMiniSat-TNN VERSION 1.0 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
add_subdirectory(cryptominisat)
add_library(ctcc_propagator STATIC ctcc_propagator.cpp)
target_link_libraries(ctcc_propagator PRIVATE cryptominisat)
add_executable(cms-tnn main.cpp)
target_link_libraries(cms-tnn PRIVATE cryptominisat ctcc_propagator)
add_executable(cms-cnf main_cnf.cpp)
target_link_libraries(cms-cnf PRIVATE cryptominisat)
